/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Default: typeof import('./src/components/layouts/default.vue')['default']
    Delete: typeof import('./src/components/entity/task/list/item/delete.vue')['default']
    Filter: typeof import('./src/components/entity/task/ui/filter.vue')['default']
    FilterList: typeof import('./src/components/entity/task/list/filter-list.vue')['default']
    Form: typeof import('./src/components/entity/task/create/form.vue')['default']
    Header: typeof import('./src/components/entity/task/list/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./src/components/entity/task/list/item.vue')['default']
    Provider: typeof import('./src/components/layouts/provider.vue')['default']
    Stats: typeof import('./src/components/entity/task/list/stats.vue')['default']
  }
}
